export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const RESET_ALL_AUTH_REDUCER = 'RESET_ALL_AUTH_REDUCER';

//COMMON ACTION
export const GET_USER = 'GET_USER';
export const GET_ABSENTS = 'GET_ABSENTS';
export const GET_ABSENT_BY_ID = 'GET_ABSENT_BY_ID';
export const GET_LATEST_ABSENTS = 'GET_LATEST_ABSENTS';
export const GET_SALDO_KAS = 'GET_SALDO_KAS';
export const GET_KAS_TRANSACTION = 'GET_KAS_TRANSACTION';
export const OFF_WORK = 'OFF_WORK';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const RESET_ALL_COMMON_REDUCER = 'RESET_ALL_COMMON_REDUCER';

//Transaction Action
export const ABSENT_IN = 'ABSENT_IN';
export const ABSENT_OUT = 'ABSENT_OUT';
export const PAYING_KAS = 'PAYING_KAS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const RESET_ALL_TRANSACTION_REDUCER = 'RESET_ALL_TRANSACTION_REDUCER';

export const GET_ATTENDANCE_TAG = 'GET_ATTENDANCE_TAG';

export const GET_REIMBURSEMENT = 'GET_REIMBURSEMENT';
export const GET_SALDO_REIMBURSEMENT = 'GET_SALDO_REIMBURSEMENT';
export const INCOMING_NOTIFICATION = 'INCOMING_NOTIFICATION';

export const GET_TYPE_OFF_WORK = 'GET_TYPE_OFF_WORK';