require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AbsensiMobile' do
  config = use_native_modules!

  use_react_native!(:path => config[
    "reactNativePath"
  ])

  # pod 'React', :path => '../node_modules/react-native', :subspecs => [
  #   'Core',
  #   'CxxBridge', # Include this for RN >= 0.47
  #   'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  #   'RCTText',
  #   'RCTNetwork',
  #   'RCTWebSocket', # Needed for debugging
  #   'RCTAnimation', # Needed for FlatList and animations running on native UI thread
  #   # Add any other subspecs you want to use in your project
  # ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  # pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'


  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  target 'AbsensiMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'AbsensiMobile-tvOS' do
  # Pods for AbsensiMobile-tvOS

  target 'AbsensiMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
